name       : dleyna-core
version    : 0.6.0
release    : 8
source     :
    - git|https://github.com/intel/dleyna-core.git : 41b2e56f67b6fc9c8c256b86957d281644b9b846
license    : LGPL-2.1-only
component  : programming.library
summary    : Library of utility functions that are used by the higher level dLeyna
description: |
    Library of utility functions that are used by the higher level dLeyna
builddeps  :
    - pkgconfig(gupnp-1.2)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
