name       : dleyna-core
version    : 0.6.0
release    : 4
source     :
    - https://github.com/intel/dleyna-core/archive/v0.6.0.tar.gz : e999ef3829837b777d04dc964e564704327533f5401b158ce1da8ab9be5cb61b
license    : LGPL-2.1-only
component  : programming.library
summary    : Library of utility functions that are used by the higher level dLeyna
description: |
    Library of utility functions that are used by the higher level dLeyna
builddeps  :
    - pkgconfig(gupnp-1.0)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
