name       : dleyna-core
version    : 0.5.0
release    : 1
source     :
    - https://01.org/sites/default/files/downloads/dleyna/dleyna-core-0.5.0.tar.gz : de3027acf5718eae837b5f126bd49b8111189fb075e040d43b480d2b9b114aae
license    : LGPL-2.1
summary    : Library of utility functions that are used by the higher level dLeyna
description: |
    Library of utility functions that are used by the higher level dLeyna
builddeps  :
    - pkgconfig(gupnp-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
