name       : dleyna-core
version    : 0.6.0
release    : 2
source     :
    - https://01.org/sites/default/files/downloads/dleyna/dleyna-core-0.6.0.tar_3.gz : e999ef3829837b777d04dc964e564704327533f5401b158ce1da8ab9be5cb61b
license    : LGPL-2.1
component  : programming.library
summary    : Library of utility functions that are used by the higher level dLeyna
description: |
    Library of utility functions that are used by the higher level dLeyna
builddeps  :
    - pkgconfig(gupnp-1.0)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
